apiVersion: v1
kind: ConfigMap
metadata:
  name: institution-service-config
  labels:
    app: mediq
    service: institution-service
data:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "8606"
  
  # RabbitMQ Configuration
  rabbitmq-url: "amqp://rabbitmq:5672"
  rabbitmq-queue: "institution_service_queue"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: "5000"
  HEALTH_CHECK_INTERVAL: "30000"
  
  # Database Configuration (non-sensitive)
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  DB_CONNECTION_TIMEOUT: "60000"
  DB_IDLE_TIMEOUT: "300000"
  
  # Service Configuration
  SERVICE_NAME: "institution-service"
  SERVICE_VERSION: "1.0.0"
  
  # API Configuration
  API_PREFIX: "api"
  API_VERSION: "v1"
  SWAGGER_ENABLED: "true"
  
  # Rate Limiting
  RATE_LIMIT_WINDOW_MS: "900000"  # 15 minutes
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Request Timeout
  REQUEST_TIMEOUT: "30000"  # 30 seconds
  
  # CORS Configuration
  CORS_ENABLED: "true"
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE"
  CORS_CREDENTIALS: "false"
